name: Data Preparation and Model Training

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare_and_train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Preparation
      run: |
        python data_preparation.py

    - name: Run Model Training
      run: |
        python model_training.py

    - name: Upload Fine-Tuned Model as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fine_tuned_gpt2
        path: ./fine_tuned_gpt2
